### ISSUE TITLE
json-rpc: how to get feedback from the ldk side?

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#106]
When lampo will run a command there is a necessity to handle the ldk result in some way.

For instance, while running `fundchannel` there are the following cases that are not handled: 

- An error occurs and it should be returned from the command line, e.g: There are not enough funds to create a transaction;
- All goes well but while calling the `fundchannel` we do not have information, so we should wait for a ldk event like `ChannelPending` and then return the error to the user

**Comment by Harshit933** [comment]
I'll take a look.

**Comment by vincenzopalazzo** [comment]
Implemented in https://github.com/vincenzopalazzo/lampo.rs/pull/197
