### ISSUE TITLE
Crash caused when the port is already in use

### ISSUE THREAD

**Issue by Harshit933** [vincenzopalazzo/lampo.rs#172]
I was using my lightning node with the same port as my lampo node.

```
2023-12-23T18:52:14.087Z INFO jsonrpc starting server on /home/harshit/.lampo/testnet/lampod.socket. [lampo-jsonrpc/src/lib.rs:178]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', lampod/src/ln/peer_manager.rs:148:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vincenzopalazzo** [comment]
@Harshit933 do you have a path for it? I my putting this for the next release in March

**Comment by Harshit933** [comment]
I will take it up.

**Comment by Psycho-Pirate** [comment]
I would like to work on this. What is the desired outcome if the port specified is already in use?

**Comment by Harshit933** [comment]
I think we should just return some error stating something like "Please specify another port"

**Comment by vincenzopalazzo** [comment]
>I would like to work on this. What is the desired outcome if the port specified is already in use?

Currently, we just call `.unwrap()` which in rust words means, I do not care because this will never happen, we should instead return the error to the caller of the method.

>I think we should just return some error stating something like "Please specify another port"

Mh @Harshit933 I do not like print the custom error, we should just print the raw error that it is returned to us by the rust/tokio library

**Comment by Harshit933** [comment]
> Mh @Harshit933 I do not like print the custom error, we should just print the raw error that it is returned to us by the rust/tokio library

Agreed, that would be better as all the other components inside lampo does not return any custom error

**Comment by vincenzopalazzo** [comment]
Moving this to the next release in june

**Comment by vincenzopalazzo** [comment]
>Hey I would like to work on this issue, is it up for grabs?

There is no assignment issue, you just fix the issue with a PR, so anyone that want to work on it it free to work on it
