### ISSUE TITLE
ask the seed to the user not as a option parameter

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#211]
Currently we have a privacy leak but we are not on mainet so we are safe.

We should ask the user to tell us the words in a very interactive way and not with command line parameter.

**Comment by lazyfuhrer** [comment]
How would you like the user to tell the words ? @vincenzopalazzo 
example:
```bash
$ lampod-cli --network <network> --restore-wallet
- Enter your BIP-39 seed words one by one.
$ Word (1): book
$ Word (2): pool
....
$ Word (12): nice
```
I'm willing to work on this.
