### ISSUE TITLE
jsonrpc: return a warning everytime a json response get handled

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#230]
This gives me the warning everytime I run `lampo-cli --network regtest getinfo`. 
```
2024-05-24T16:13:35.386Z WARN jsonrpc event invalid: Event { key: Connect, source: Source { fd: 15, events: 519, revents: 32 } }. [lampo-jsonrpc/src/lib.rs:281]
```

This is the basic flow of events whenever I am querying the node. 
1. `RPCEvent::Accept`
2. `RPCEvent::Connect && event.is_readable()`
3. `RPCEvent::Connect and the event.is_invalid()` -> This throws the warning.

_Originally posted by @Harshit933 in https://github.com/vincenzopalazzo/lampo.rs/pull/219#discussion_r1613732761_

**Comment by Harshit933** [comment]
I will take this.

**Comment by vincenzopalazzo** [comment]
I do not think this is a task for you @Harshit933, this is a problem on how we use pool at the kernel level

Or your already know how to fix it?

**Comment by Harshit933** [comment]
I do not know. But if you are working on this you would do far better than me :)

**Comment by vincenzopalazzo** [comment]
I think we should not waste time in bug that we do not know how to solve. You have already a lot of work on your plate

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/lampo.rs/pull/242
